import AppKit
import Combine
import CryptoKit

enum ClipKind: String, Codable {
    case text, image, files
}

struct ClipItem: Identifiable, Codable, Equatable {
    var id: UUID = UUID()
    var kind: ClipKind
    /// Texto plano, rutas separadas por salto de línea (archivos) o "800 × 600" (imagen).
    var text: String
    var imageName: String?
    var appBundleID: String?
    var appName: String?
    var date: Date
    var pinned: Bool = false
    /// Huella del contenido, para no guardar el mismo recorte dos veces.
    var digest: String

    var urls: [URL] {
        guard kind == .files else { return [] }
        return text.split(separator: "\n").map { URL(fileURLWithPath: String($0)) }
    }

    var preview: String {
        switch kind {
        case .text:
            let flat = text.replacingOccurrences(of: "\n", with: " ")
                           .replacingOccurrences(of: "\t", with: " ")
            let squeezed = flat.split(separator: " ", omittingEmptySubsequences: true).joined(separator: " ")
            return String(squeezed.prefix(300))
        case .files:
            return urls.map { $0.lastPathComponent }.joined(separator: ", ")
        case .image:
            return text.isEmpty ? "Imagen" : "Imagen \(text)"
        }
    }

    var isLink: Bool {
        guard kind == .text else { return false }
        let t = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !t.contains(" "), t.count > 8 else { return false }
        return t.hasPrefix("http://") || t.hasPrefix("https://")
    }

    var symbol: String {
        switch kind {
        case .text: return isLink ? "link" : "text.alignleft"
        case .image: return "photo"
        case .files: return "doc.on.doc"
        }
    }

    /// Segunda línea de la fila: de dónde salió y hace cuánto.
    var subtitle: String {
        var parts: [String] = []
        if let appName, !appName.isEmpty { parts.append(appName) }
        parts.append(ClipItem.relative.localizedString(for: date, relativeTo: Date()))
        if kind == .text {
            let n = text.count
            parts.append("\(n) \(n == 1 ? "carácter" : "caracteres")")
        }
        return parts.joined(separator: " · ")
    }

    private static let relative: RelativeDateTimeFormatter = {
        let f = RelativeDateTimeFormatter()
        f.locale = Locale(identifier: "es")
        f.unitsStyle = .short
        return f
    }()
}

/// Historial del portapapeles: vigila NSPasteboard, guarda lo copiado y lo vuelve a pegar.
@MainActor
final class ClipboardStore: ObservableObject {
    static let shared = ClipboardStore()

    @Published private(set) var items: [ClipItem] = []
    /// Texto del buscador de la pestaña.
    @Published var query: String = ""
    /// Fila resaltada (índice dentro de `visibleItems`).
    @Published var selection: Int = 0

    private let prefs = Prefs.shared
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var imageCache: [String: NSImage] = [:]
    private var saveWork: DispatchWorkItem?

    /// Apps cuyo portapapeles nunca se guarda (gestores de contraseñas y similares).
    private static let confidentialApps: Set<String> = [
        "com.agilebits.onepassword7", "com.1password.1password", "com.agilebits.onepassword",
        "com.apple.keychainaccess", "com.bitwarden.desktop", "com.dashlane.dashlanephonefinal",
        "com.lastpass.LastPass", "in.sinew.Enpass-Desktop", "com.keepassium.mac",
        "org.keepassxc.keepassxc", "com.mackieinnovations.strongbox", "com.apple.Passwords"
    ]

    /// Tipos que las apps marcan para pedir que el portapapeles no se registre.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword"
    ]

    private static let dir: URL = {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
            .appendingPathComponent("Island Effect/Clipboard", isDirectory: true)
        try? FileManager.default.createDirectory(at: base.appendingPathComponent("images"),
                                                 withIntermediateDirectories: true)
        return base
    }()
    private static var historyFile: URL { dir.appendingPathComponent("history.json") }
    private static var imagesDir: URL { dir.appendingPathComponent("images", isDirectory: true) }

    private init() {
        load()
    }

    // MARK: - Vigilancia del portapapeles

    func start() {
        guard timer == nil else { return }
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            Task { @MainActor in self?.poll() }
        }
        t.tolerance = 0.15
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard prefs.enableClipboard else { return }

        let types = Set((pb.types ?? []).map { $0.rawValue })
        if prefs.clipboardIgnoreConfidential, !types.isDisjoint(with: Self.privateTypes) { return }

        let app = NSWorkspace.shared.frontmostApplication
        if prefs.clipboardIgnoreConfidential,
           let bundle = app?.bundleIdentifier, Self.confidentialApps.contains(bundle) { return }

        guard let item = capture(from: pb, app: app) else { return }
        insert(item)
    }

    private func capture(from pb: NSPasteboard, app: NSRunningApplication?) -> ClipItem? {
        let bundleID = app?.bundleIdentifier
        let appName = app?.localizedName

        // 1. Archivos (Finder también deja un string, así que van primero).
        if let urls = pb.readObjects(forClasses: [NSURL.self],
                                     options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map { $0.standardizedFileURL.path }.joined(separator: "\n")
            return ClipItem(kind: .files, text: paths, appBundleID: bundleID, appName: appName,
                            date: Date(), digest: Self.digest(of: Data(paths.utf8)))
        }

        // 2. Imágenes.
        if prefs.clipboardKeepImages,
           let data = pb.data(forType: .png) ?? pb.data(forType: .tiff),
           let image = NSImage(data: data) {
            let digest = Self.digest(of: data)
            let size = "\(Int(image.size.width)) × \(Int(image.size.height))"
            let name = "\(digest).png"
            if let png = Self.pngData(from: image) {
                try? png.write(to: Self.imagesDir.appendingPathComponent(name))
            }
            imageCache[name] = image
            return ClipItem(kind: .image, text: size, imageName: name, appBundleID: bundleID,
                            appName: appName, date: Date(), digest: digest)
        }

        // 3. Texto.
        if let string = pb.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            return ClipItem(kind: .text, text: string, appBundleID: bundleID, appName: appName,
                            date: Date(), digest: Self.digest(of: Data(string.utf8)))
        }

        return nil
    }

    // MARK: - Lista

    private func insert(_ item: ClipItem) {
        if let index = items.firstIndex(where: { $0.digest == item.digest }) {
            // Ya lo teníamos: lo subimos arriba en vez de duplicarlo.
            var existing = items.remove(at: index)
            existing.date = item.date
            existing.appName = item.appName
            existing.appBundleID = item.appBundleID
            items.insert(existing, at: 0)
        } else {
            items.insert(item, at: 0)
        }
        trim()
        scheduleSave()
    }

    private func trim() {
        let limit = max(5, Int(prefs.clipboardMaxItems))
        var unpinned = 0
        var kept: [ClipItem] = []
        var dropped: [ClipItem] = []
        for item in items {
            if item.pinned {
                kept.append(item)
            } else if unpinned < limit {
                unpinned += 1
                kept.append(item)
            } else {
                dropped.append(item)
            }
        }
        guard !dropped.isEmpty else { return }
        items = kept
        dropped.forEach(deleteImageFile)
    }

    /// Items ordenados y filtrados por el buscador: primero los fijados.
    var visibleItems: [ClipItem] {
        let needle = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        let matched = needle.isEmpty ? items : items.filter {
            $0.preview.lowercased().contains(needle) || ($0.appName ?? "").lowercased().contains(needle)
        }
        return matched.sorted { a, b in
            if a.pinned != b.pinned { return a.pinned }
            return a.date > b.date
        }
    }

    func togglePin(_ item: ClipItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        items[index].pinned.toggle()
        trim()
        scheduleSave()
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
        deleteImageFile(item)
        clampSelection()
        scheduleSave()
    }

    func clear(keepPinned: Bool = true) {
        let removed = items.filter { keepPinned ? !$0.pinned : true }
        items = keepPinned ? items.filter { $0.pinned } : []
        removed.forEach(deleteImageFile)
        clampSelection()
        scheduleSave()
    }

    func clampSelection() {
        let count = visibleItems.count
        selection = count == 0 ? 0 : min(max(0, selection), count - 1)
    }

    func move(by delta: Int) {
        let count = visibleItems.count
        guard count > 0 else { return }
        selection = (selection + delta + count) % count
    }

    var selectedItem: ClipItem? {
        let list = visibleItems
        guard list.indices.contains(selection) else { return nil }
        return list[selection]
    }

    // MARK: - Pegar

    /// Deja el ítem en el portapapeles del sistema (así el ⌘V siguiente también lo pega).
    func writeToPasteboard(_ item: ClipItem) {
        let pb = NSPasteboard.general
        pb.clearContents()
        switch item.kind {
        case .text:
            pb.setString(item.text, forType: .string)
        case .files:
            let urls = item.urls.filter { FileManager.default.fileExists(atPath: $0.path) }
            if urls.isEmpty {
                pb.setString(item.text, forType: .string)
            } else {
                pb.writeObjects(urls.map { $0 as NSURL })
            }
        case .image:
            if let image = image(for: item), let png = Self.pngData(from: image) {
                pb.setData(png, forType: .png)
            }
        }
        // No queremos que el vigilante lo tome como una copia nueva.
        lastChangeCount = pb.changeCount

        if let index = items.firstIndex(where: { $0.id == item.id }) {
            var updated = items.remove(at: index)
            updated.date = Date()
            items.insert(updated, at: 0)
            scheduleSave()
        }
    }

    /// Copia el ítem y, si se puede, lo pega en la app que estaba adelante.
    func use(_ item: ClipItem) {
        writeToPasteboard(item)
        NotchController.shared.dismissClipboard(pasting: prefs.clipboardAutoPaste)
    }

    // MARK: - Imágenes

    func image(for item: ClipItem) -> NSImage? {
        guard let name = item.imageName else { return nil }
        if let cached = imageCache[name] { return cached }
        let url = Self.imagesDir.appendingPathComponent(name)
        guard let image = NSImage(contentsOf: url) else { return nil }
        imageCache[name] = image
        return image
    }

    private func deleteImageFile(_ item: ClipItem) {
        guard let name = item.imageName else { return }
        imageCache[name] = nil
        try? FileManager.default.removeItem(at: Self.imagesDir.appendingPathComponent(name))
    }

    private static func pngData(from image: NSImage) -> Data? {
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private static func digest(of data: Data) -> String {
        SHA256.hash(data: data).prefix(12).map { String(format: "%02x", $0) }.joined()
    }

    // MARK: - Persistencia

    private func scheduleSave() {
        saveWork?.cancel()
        let work = DispatchWorkItem { [weak self] in Task { @MainActor in self?.save() } }
        saveWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.6, execute: work)
    }

    private func save() {
        guard prefs.clipboardPersists else { return }
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        guard let data = try? encoder.encode(items) else { return }
        try? data.write(to: Self.historyFile, options: .atomic)
    }

    private func load() {
        guard prefs.clipboardPersists,
              let data = try? Data(contentsOf: Self.historyFile) else { return }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let saved = try? decoder.decode([ClipItem].self, from: data) else { return }
        // Descarta imágenes cuyo archivo ya no está.
        items = saved.filter { item in
            guard let name = item.imageName else { return true }
            return FileManager.default.fileExists(atPath: Self.imagesDir.appendingPathComponent(name).path)
        }
    }

    /// Borra todo, incluido lo guardado en disco.
    func purge() {
        items = []
        imageCache = [:]
        try? FileManager.default.removeItem(at: Self.imagesDir)
        try? FileManager.default.createDirectory(at: Self.imagesDir, withIntermediateDirectories: true)
        try? FileManager.default.removeItem(at: Self.historyFile)
    }
}
